[build]
builder = "RAILPACK"
buildCommand = "npm run build"
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
useLegacyStacker = false
ipv6EgressEnabled = false

[deploy.multiRegionConfig]
enabled = true

[deploy.restartPolicy]
type = "ON_FAILURE"
maxRetries = 10

